"""Type stubs for the PyO3 extension module ``calybris._core``.

Hand-maintained to mirror ``bindings/python/src/lib.rs``. The Rust kernel is
the source of truth; these stubs give mypy and IDEs the shapes of the
Rust-backed classes, methods, and constants. Dict-returning methods use
``dict[str, Any]`` because the payload keys are documented in ``docs/CALY_PROOF.md``
and the audit/budget guides rather than fixed here.
"""

from typing import Any, Literal

# ─────────────────────────── constants ────────────────────────────

ALL_PROVIDERS: int
ALL_REGIONS: int
MICROCENTS_PER_CENT: int

ACTION_EXECUTE_REQUESTED: int
ACTION_SUBSTITUTE: int
ACTION_REJECT: int

REASON_REQUESTED_MODEL_MAXIMIZES_UTILITY: int
REASON_ALTERNATIVE_MAXIMIZES_UTILITY: int
REASON_RISK_HARD_LIMIT: int
REASON_CONFIDENCE_HARD_LIMIT: int
REASON_NO_ENABLED_MODEL: int
REASON_QUALITY_CONSTRAINT: int
REASON_LATENCY_CONSTRAINT: int
REASON_CAPABILITY_CONSTRAINT: int
REASON_PROVIDER_CONSTRAINT: int
REASON_REGION_CONSTRAINT: int
REASON_BUDGET_CONSTRAINT: int
REASON_NON_POSITIVE_UTILITY: int
REASON_RISK_CEILING_CONSTRAINT: int

# ──────────────────────────── classes ─────────────────────────────

class KernelModel:
    """One candidate in a policy catalog. All fields are readable and writable."""

    model_id: int
    provider_id: int
    quality_bps: int
    risk_ceiling_bps: int
    enabled: int
    p95_latency_ms: int
    capabilities: int
    region_mask: int
    input_cost_microunits_per_million_tokens: int
    output_cost_microunits_per_million_tokens: int

    def __init__(
        self,
        model_id: int,
        provider_id: int,
        quality_bps: int,
        risk_ceiling_bps: int,
        enabled: int,
        p95_latency_ms: int,
        capabilities: int,
        region_mask: int,
        input_cost_microunits_per_million_tokens: int,
        output_cost_microunits_per_million_tokens: int,
    ) -> None: ...
    def as_dict(self) -> dict[str, Any]: ...
    def __eq__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...

class KernelInput:
    """A typed decision request. Constructing one validates its fields."""

    request_sequence: int
    requested_model_id: int
    input_tokens: int
    output_tokens: int
    business_value_microunits: int
    budget_limit_microunits: int
    risk_bps: int
    confidence_bps: int
    minimum_quality_bps: int
    max_p95_latency_ms: int
    required_capabilities: int
    allowed_provider_mask: int
    required_region_mask: int

    def __init__(
        self,
        request_sequence: int,
        requested_model_id: int,
        input_tokens: int,
        output_tokens: int,
        business_value_microunits: int,
        budget_limit_microunits: int,
        risk_bps: int,
        confidence_bps: int,
        minimum_quality_bps: int,
        max_p95_latency_ms: int,
        required_capabilities: int,
        allowed_provider_mask: int,
        required_region_mask: int,
    ) -> None: ...
    def as_dict(self) -> dict[str, Any]: ...
    def __eq__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...

class KernelDecision:
    """The kernel's output for one request. Returned by ``PolicySnapshot.prescribe``;
    not constructed directly."""

    @property
    def request_sequence(self) -> int: ...
    @property
    def action(self) -> str: ...
    @property
    def action_code(self) -> int: ...
    @property
    def reason(self) -> str: ...
    @property
    def reason_code(self) -> int: ...
    @property
    def selected_model_id(self) -> int: ...
    @property
    def selected_model_index(self) -> int: ...
    @property
    def estimated_cost_microunits(self) -> int: ...
    @property
    def expected_utility_microunits(self) -> int: ...
    @property
    def counterfactual_model_id(self) -> int: ...
    @property
    def counterfactual_utility_microunits(self) -> int: ...
    @property
    def evaluated_models(self) -> int: ...
    @property
    def eligible_models(self) -> int: ...
    @property
    def policy_epoch(self) -> int: ...
    @property
    def catalog_epoch(self) -> int: ...
    def is_executable(self) -> bool: ...
    def is_rejected(self) -> bool: ...
    def is_requested_execution(self) -> bool: ...
    def is_substitution(self) -> bool: ...
    def as_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...

class PolicySnapshot:
    """An immutable policy + catalog. Evaluates requests and emits audit proofs."""

    def __init__(
        self,
        policy_epoch: int,
        catalog_epoch: int,
        hard_risk_limit_bps: int,
        minimum_confidence_bps: int,
        risk_penalty_multiplier_bps: int,
        latency_penalty_microunits_per_ms: int,
        models: list[KernelModel],
    ) -> None: ...
    @property
    def policy_epoch(self) -> int: ...
    @property
    def catalog_epoch(self) -> int: ...
    @property
    def hard_risk_limit_bps(self) -> int: ...
    @property
    def minimum_confidence_bps(self) -> int: ...
    @property
    def risk_penalty_multiplier_bps(self) -> int: ...
    @property
    def latency_penalty_microunits_per_ms(self) -> int: ...
    def prescribe(self, input: KernelInput) -> KernelDecision: ...
    def prescribe_with_trace(
        self, input: KernelInput
    ) -> tuple[KernelDecision, dict[str, Any]]: ...
    def prescribe_batch(self, inputs: list[KernelInput]) -> list[KernelDecision]: ...
    def utility_for_model(self, input: KernelInput, model_id: int) -> int | None: ...
    def counterfactual_utility(
        self, input: KernelInput, model_id: int
    ) -> int | None: ...
    def audit_bundle(
        self, input: KernelInput, decision: KernelDecision
    ) -> dict[str, Any]: ...
    def verified_audit_bundle(
        self, input: KernelInput, decision: KernelDecision
    ) -> dict[str, Any]:
        """Fail-closed: raises ``ValueError`` if the decision does not replay."""
        ...
    def verify(
        self, input: KernelInput, decision: KernelDecision
    ) -> dict[str, Any]: ...
    def verify_status(
        self, input: KernelInput, decision: KernelDecision
    ) -> Literal["valid", "mismatch", "digest_mismatch"]: ...
    def proof_envelope(
        self, input: KernelInput, decision: KernelDecision
    ) -> dict[str, Any]: ...
    def models(self) -> list[KernelModel]: ...
    def model_count(self) -> int: ...
    def fingerprint(self) -> str: ...
    def as_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...

class BudgetEngine:
    """CAS reserve/commit/release ledger with conservation proofs."""

    def __init__(self) -> None: ...
    def ensure_tenant(self, tenant_id: str, budget_microcents: int) -> None: ...
    def set_max_reserved_microcents(
        self, tenant_id: str, max_microcents: int
    ) -> None: ...
    def top_up_tenant(self, tenant_id: str, amount_microcents: int) -> dict[str, Any]: ...
    def try_reserve(self, tenant_id: str, amount_microcents: int) -> dict[str, Any]: ...
    def commit(self, reservation_id: int, actual_microcents: int) -> dict[str, Any]: ...
    def release(self, reservation_id: int) -> dict[str, Any]: ...
    def certify(self) -> dict[str, Any]: ...
    def snapshot(self) -> dict[str, Any]: ...
    def prove_conservation(self) -> dict[str, Any]: ...
    def verify_conservation(self) -> dict[str, Any]: ...
    def initial_microcents(self, tenant_id: str) -> int | None: ...
    def remaining_microcents(self, tenant_id: str) -> int | None: ...
    def reserved_microcents(self, tenant_id: str) -> int: ...
    def committed_microcents(self, tenant_id: str) -> int | None: ...
    def tenant_count(self) -> int: ...
    def active_reservations(self) -> int: ...
    def __repr__(self) -> str: ...
