"""Type stubs for the PyO3 extension module ``calybris._core``.

Hand-maintained to mirror ``bindings/python/src/lib.rs``. The Rust kernel is
the source of truth; these stubs give mypy and IDEs the shapes of the
Rust-backed classes, methods, and constants. Dict-returning methods use
``dict[str, Any]`` because the payload keys are documented in ``docs/CALY_PROOF.md``
and the audit/budget guides rather than fixed here.
"""

from os import PathLike
from typing import Any, Literal

# ─────────────────────────── constants ────────────────────────────

ALL_PROVIDERS: int
ALL_REGIONS: int
MICROCENTS_PER_CENT: int

ACTION_EXECUTE_REQUESTED: int
ACTION_SUBSTITUTE: int
ACTION_REJECT: int

class CalybrisError(Exception): ...
class ArtifactValidationError(CalybrisError): ...
class DecisionVerificationError(CalybrisError): ...
class ReceiptError(CalybrisError): ...
class ProvenanceError(CalybrisError): ...
class WalError(CalybrisError): ...
class PersistenceError(CalybrisError): ...
class StateTrajectoryError(CalybrisError): ...

REASON_REQUESTED_MODEL_MAXIMIZES_UTILITY: int
REASON_ALTERNATIVE_MAXIMIZES_UTILITY: int
REASON_RISK_HARD_LIMIT: int
REASON_CONFIDENCE_HARD_LIMIT: int
REASON_NO_ENABLED_MODEL: int
REASON_QUALITY_CONSTRAINT: int
REASON_LATENCY_CONSTRAINT: int
REASON_CAPABILITY_CONSTRAINT: int
REASON_PROVIDER_CONSTRAINT: int
REASON_REGION_CONSTRAINT: int
REASON_BUDGET_CONSTRAINT: int
REASON_NON_POSITIVE_UTILITY: int
REASON_RISK_CEILING_CONSTRAINT: int

# ──────────────────────────── classes ─────────────────────────────

class KernelModel:
    """One candidate in a policy catalog. All fields are readable and writable."""

    model_id: int
    provider_id: int
    quality_bps: int
    risk_ceiling_bps: int
    enabled: int
    p95_latency_ms: int
    capabilities: int
    region_mask: int
    input_cost_microunits_per_million_tokens: int
    output_cost_microunits_per_million_tokens: int

    def __init__(
        self,
        model_id: int,
        provider_id: int,
        quality_bps: int,
        risk_ceiling_bps: int,
        enabled: int,
        p95_latency_ms: int,
        capabilities: int,
        region_mask: int,
        input_cost_microunits_per_million_tokens: int,
        output_cost_microunits_per_million_tokens: int,
    ) -> None: ...
    def as_dict(self) -> dict[str, Any]: ...
    def __eq__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...

class KernelInput:
    """A typed decision request. Constructing one validates its fields."""

    request_sequence: int
    requested_model_id: int
    input_tokens: int
    output_tokens: int
    business_value_microunits: int
    budget_limit_microunits: int
    risk_bps: int
    confidence_bps: int
    minimum_quality_bps: int
    max_p95_latency_ms: int
    required_capabilities: int
    allowed_provider_mask: int
    required_region_mask: int

    def __init__(
        self,
        request_sequence: int,
        requested_model_id: int,
        input_tokens: int,
        output_tokens: int,
        business_value_microunits: int,
        budget_limit_microunits: int,
        risk_bps: int,
        confidence_bps: int,
        minimum_quality_bps: int,
        max_p95_latency_ms: int,
        required_capabilities: int,
        allowed_provider_mask: int,
        required_region_mask: int,
    ) -> None: ...
    def as_dict(self) -> dict[str, Any]: ...
    def __eq__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...

class KernelDecision:
    """The kernel's output for one request. Returned by ``PolicySnapshot.prescribe``;
    not constructed directly."""

    @property
    def request_sequence(self) -> int: ...
    @property
    def action(self) -> str: ...
    @property
    def action_code(self) -> int: ...
    @property
    def reason(self) -> str: ...
    @property
    def reason_code(self) -> int: ...
    @property
    def selected_model_id(self) -> int: ...
    @property
    def selected_model_index(self) -> int: ...
    @property
    def estimated_cost_microunits(self) -> int: ...
    @property
    def expected_utility_microunits(self) -> int: ...
    @property
    def counterfactual_model_id(self) -> int: ...
    @property
    def counterfactual_utility_microunits(self) -> int: ...
    @property
    def evaluated_models(self) -> int: ...
    @property
    def eligible_models(self) -> int: ...
    @property
    def policy_epoch(self) -> int: ...
    @property
    def catalog_epoch(self) -> int: ...
    def is_executable(self) -> bool: ...
    def is_rejected(self) -> bool: ...
    def is_requested_execution(self) -> bool: ...
    def is_substitution(self) -> bool: ...
    def as_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...

class PolicySnapshot:
    """An immutable policy + catalog. Evaluates requests and emits audit proofs."""

    def __init__(
        self,
        policy_epoch: int,
        catalog_epoch: int,
        hard_risk_limit_bps: int,
        minimum_confidence_bps: int,
        risk_penalty_multiplier_bps: int,
        latency_penalty_microunits_per_ms: int,
        models: list[KernelModel],
    ) -> None: ...
    @property
    def policy_epoch(self) -> int: ...
    @property
    def catalog_epoch(self) -> int: ...
    @property
    def hard_risk_limit_bps(self) -> int: ...
    @property
    def minimum_confidence_bps(self) -> int: ...
    @property
    def risk_penalty_multiplier_bps(self) -> int: ...
    @property
    def latency_penalty_microunits_per_ms(self) -> int: ...
    def prescribe(self, input: KernelInput) -> KernelDecision: ...
    def prescribe_with_trace(
        self, input: KernelInput
    ) -> tuple[KernelDecision, dict[str, Any]]: ...
    def prescribe_batch(self, inputs: list[KernelInput]) -> list[KernelDecision]: ...
    def utility_for_model(self, input: KernelInput, model_id: int) -> int | None: ...
    def counterfactual_utility(
        self, input: KernelInput, model_id: int
    ) -> int | None: ...
    def audit_bundle(
        self, input: KernelInput, decision: KernelDecision
    ) -> dict[str, Any]: ...
    def verified_audit_bundle(
        self, input: KernelInput, decision: KernelDecision
    ) -> dict[str, Any]:
        """Fail-closed: raises ``ValueError`` if the decision does not replay."""
        ...
    def verify(
        self, input: KernelInput, decision: KernelDecision
    ) -> dict[str, Any]: ...
    def verify_status(
        self, input: KernelInput, decision: KernelDecision
    ) -> Literal["valid", "mismatch", "digest_mismatch"]: ...
    def proof_envelope(
        self, input: KernelInput, decision: KernelDecision
    ) -> dict[str, Any]: ...
    def sign_policy(
        self, signing_key_bytes: bytes, signer_id: str, signed_at_epoch_ms: int
    ) -> SignedPolicy: ...
    def stateful_audit_bundle(
        self,
        input: KernelInput,
        decision: KernelDecision,
        transition: StateTransition,
    ) -> StatefulAuditBundle: ...
    def issue_receipt(
        self,
        input: KernelInput,
        decision: KernelDecision,
        *,
        state: ReceiptState | None = None,
        wal: ReceiptWal | None = None,
    ) -> DecisionReceipt: ...
    def models(self) -> list[KernelModel]: ...
    def model_count(self) -> int: ...
    def fingerprint(self) -> str: ...
    def as_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...

class BudgetEngine:
    """CAS reserve/commit/release ledger with conservation proofs."""

    def __init__(self) -> None: ...
    def ensure_tenant(self, tenant_id: str, budget_microcents: int) -> None: ...
    def set_max_reserved_microcents(
        self, tenant_id: str, max_microcents: int
    ) -> None: ...
    def top_up_tenant(self, tenant_id: str, amount_microcents: int) -> dict[str, Any]: ...
    def try_reserve(self, tenant_id: str, amount_microcents: int) -> dict[str, Any]: ...
    def commit(self, reservation_id: int, actual_microcents: int) -> dict[str, Any]: ...
    def release(self, reservation_id: int) -> dict[str, Any]: ...
    def certify(self) -> dict[str, Any]: ...
    def checkpoint(self, path: str | PathLike[str]) -> dict[str, Any]: ...
    def checkpoint_with_wal(
        self, path: str | PathLike[str], wal_sequence: int
    ) -> dict[str, Any]: ...
    def restore(self, path: str | PathLike[str]) -> dict[str, Any]: ...
    def snapshot(self) -> dict[str, Any]: ...
    def prove_conservation(self) -> dict[str, Any]: ...
    def verify_conservation(self) -> dict[str, Any]: ...
    def initial_microcents(self, tenant_id: str) -> int | None: ...
    def remaining_microcents(self, tenant_id: str) -> int | None: ...
    def reserved_microcents(self, tenant_id: str) -> int: ...
    def committed_microcents(self, tenant_id: str) -> int | None: ...
    def tenant_count(self) -> int: ...
    def active_reservations(self) -> int: ...
    def __repr__(self) -> str: ...

class StateTransition:
    @property
    def step(self) -> int: ...
    @property
    def digest_before_hex(self) -> str: ...
    @property
    def digest_after_hex(self) -> str: ...
    def as_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...

class StateChain:
    def __init__(self, initial_state: bytes) -> None: ...
    @staticmethod
    def genesis(initial_state: bytes) -> StateChain: ...
    @property
    def step(self) -> int: ...
    @property
    def last_digest_hex(self) -> str: ...
    def advance(self, next_state: bytes) -> StateTransition: ...
    def __repr__(self) -> str: ...

class StatefulAuditBundle:
    @property
    def step(self) -> int: ...
    @property
    def state_digest_before_hex(self) -> str: ...
    @property
    def state_digest_after_hex(self) -> str: ...
    @property
    def replay_valid(self) -> bool: ...
    def as_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...

class ReceiptState:
    def __init__(
        self,
        step: int,
        state_digest_before_hex: str,
        state_digest_after_hex: str,
    ) -> None: ...
    @staticmethod
    def from_transition(transition: StateTransition) -> ReceiptState: ...
    @property
    def step(self) -> int: ...
    @property
    def state_digest_before_hex(self) -> str: ...
    @property
    def state_digest_after_hex(self) -> str: ...
    def as_dict(self) -> dict[str, Any]: ...

class ReceiptWal:
    def __init__(self, sequence: int, entry_hash: str) -> None: ...
    @property
    def sequence(self) -> int: ...
    @property
    def entry_hash(self) -> str: ...
    def as_dict(self) -> dict[str, Any]: ...

class SignedPolicy:
    @property
    def policy_digest_hex(self) -> str: ...
    @property
    def signer_id(self) -> str: ...
    @property
    def signed_at_epoch_ms(self) -> int: ...
    @property
    def public_key_hex(self) -> str: ...
    @property
    def signature_hex(self) -> str: ...
    def verify(self, snapshot: PolicySnapshot, trusted_public_key: bytes) -> None: ...
    def to_json(self) -> str: ...
    @staticmethod
    def from_json(value: str) -> SignedPolicy: ...
    def as_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...

class DecisionReceipt:
    @property
    def schema_version(self) -> str: ...
    @property
    def policy_epoch(self) -> int: ...
    @property
    def catalog_epoch(self) -> int: ...
    @property
    def policy_digest_hex(self) -> str: ...
    @property
    def input_digest_hex(self) -> str: ...
    @property
    def decision_digest_hex(self) -> str: ...
    @property
    def replay_valid(self) -> bool: ...
    @property
    def claims_digest_hex(self) -> str: ...
    @property
    def signer_id(self) -> str | None: ...
    @property
    def signed_at_epoch_ms(self) -> int | None: ...
    @property
    def public_key_hex(self) -> str | None: ...
    @property
    def signature_hex(self) -> str | None: ...
    @property
    def state(self) -> ReceiptState | None: ...
    @property
    def wal(self) -> ReceiptWal | None: ...
    def sign(
        self, signing_key_bytes: bytes, signer_id: str, signed_at_epoch_ms: int
    ) -> None: ...
    def verify(
        self,
        snapshot: PolicySnapshot,
        input: KernelInput,
        decision: KernelDecision,
    ) -> None: ...
    def verify_signature(self, trusted_public_key: bytes) -> None: ...
    def verify_full(
        self,
        snapshot: PolicySnapshot,
        input: KernelInput,
        decision: KernelDecision,
        trusted_public_key: bytes,
        expected_state: ReceiptState,
        expected_wal: ReceiptWal,
    ) -> None: ...
    def verify_wal(self, sequence: int, entry_hash: str) -> None: ...
    def verify_state(
        self,
        step: int,
        state_digest_before_hex: str,
        state_digest_after_hex: str,
    ) -> None: ...
    def to_json(self) -> str: ...
    @staticmethod
    def from_json(value: str) -> DecisionReceipt: ...
    def as_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...

class WalAnchor:
    @property
    def schema_version(self) -> str: ...
    @property
    def sequence(self) -> int: ...
    @property
    def last_hash(self) -> str: ...
    @property
    def keyed(self) -> bool: ...
    def save(self, path: str | PathLike[str]) -> None: ...
    @staticmethod
    def load(path: str | PathLike[str]) -> WalAnchor: ...
    def as_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...

class WalEntry:
    sequence: int
    previous_hash: str
    entry_hash: str
    def receipt_anchor(self) -> ReceiptWal: ...
    def as_dict(self) -> dict[str, Any]: ...

class AuditedWal:
    def __init__(
        self,
        path: str | PathLike[str],
        *,
        hmac_key: bytes | None = None,
    ) -> None: ...
    @property
    def sequence(self) -> int: ...
    @property
    def entry_count(self) -> int: ...
    @property
    def last_hash(self) -> str: ...
    def append_verified(
        self,
        snapshot: PolicySnapshot,
        input: KernelInput,
        decision: KernelDecision,
        metadata_json: str,
    ) -> WalEntry: ...
    def flush(self) -> None: ...
    def sync(self) -> None: ...
    def flush_and_sync(self) -> None: ...
    def anchor(self) -> WalAnchor: ...
    def close(self, *, sync: bool = True) -> None: ...
    def __repr__(self) -> str: ...

def verify_audited_wal(
    path: str | PathLike[str],
    *,
    hmac_key: bytes | None = None,
    anchor: WalAnchor | None = None,
) -> tuple[int, str]: ...

def replay_verify_audited_wal(
    path: str | PathLike[str],
    snapshot: PolicySnapshot,
    *,
    hmac_key: bytes | None = None,
) -> list[dict[str, Any]]: ...

def verify_state_trajectory(bundles: list[StatefulAuditBundle]) -> None: ...
def verify_complete_state_trajectory(
    initial_state_bytes: bytes,
    expected_final_step: int,
    bundles: list[StatefulAuditBundle],
) -> None: ...
def verify_state_trajectory_fragment(
    anchor_step: int,
    anchor_digest_hex: str,
    bundles: list[StatefulAuditBundle],
) -> None: ...

def plan_recovery(
    snapshot_path: str | PathLike[str],
    wal_path: str | PathLike[str],
    *,
    hmac_key: bytes | None = None,
    anchor: WalAnchor | None = None,
) -> dict[str, Any]: ...

def public_key_from_signing_key(signing_key_bytes: bytes) -> bytes: ...
